### ISSUE TITLE
Rationale for issuer unlinkability weakness

### ISSUE THREAD

**Issue by sander-cb** [AltmannPeter/privacy-key-management#1]
We currently have the Weak-Issuer-Unlinkability objective. What is the rationale for calling it weak? That is, what features would make it normal unlinkability or strong unlinkability?

**Comment by sander** [comment]
Got an answer via email: it’s weak since it only unlinkable across issuers. A single issuer can still link two attestations back to the same subject, beyond what the attributes themselves reveal.
