### ISSUE TITLE
Relation to ARKG

### ISSUE THREAD

**Issue by sander** [AltmannPeter/privacy-key-management#5]
I have just reviewed [draft-bradleylundberg-cfrg-arkg-latest](https://yubico.github.io/arkg-rfc/draft-bradleylundberg-cfrg-arkg.html) from 2024-03-18. Here are my notes. 

ARKG addresses the same use case and can be considered a generalization of HDKD, enabling the use of separate algorithms for KEM (in the HDKD case, ECDH) and for key blinding (in the HDKD case, computing the derived PoP key). We don’t need this for the simplest P-256 use case, but it could be nice later on.

Instead of just using the issuer public key as key handle and the index as application info, ARKG adds a MAC tag to the key handle so that the user can verify correctness between deriving the blind and using their PoP key. I like that the protocol is deliberate about protecting integrity of the key handle, but in the EUDIW case we will already do this by sealing the attestation containing the PoP key. Perhaps we’d need to make the MAC optional. 

So far ARKG under “Using elliptic curve arithmetic for key blinding” only supports (in HDKD lingo) additive blinding. It should be easy to add multiplicative blinding as well. I’d like to see this reflected explicitly in the `BL` identifiers.

About reusing a single curve point for both the KEM as the PoP key like we propose in HDKD, the ARKG authors write:

> TODO: Caveats? I think I read in some paper or thesis about specific drawbacks of using the same key for both.

We should figure this out indeed. There are some potentially relevant publications about using a same scalar for ECDH as for Schnorr signing in the context of the Signal protocol and the Age encryption tool.

Let’s discuss what this all means for the specification of HDKD algorithms and protocols and how we can collaborate.

**Comment by sander** [comment]
Regarding the last point:

> In theory, under some circumstances it is safe to use a key pair to produce signatures and also use the same key pair within certain Diffie-Hellman based protocols \[15]. In practice this is a complicated topic requiring careful analysis, and is outside the scope of the current document.
>
> […]
>
> \[15] J. P. Degabriele, A. Lehmann, K. G. Paterson, N. P. Smart, and M. Strefler, “On the Joint Security of Encryption and Signature in EMV.” Cryptology ePrint Archive, Report 2011/615, 2011. http://eprint.iacr.org/2011/615

https://signal.org/docs/specifications/xeddsa/

**Comment by AltmannPeter** [comment]
> We should figure this out indeed. There are some potentially relevant publications about using a same scalar for ECDH as for Schnorr signing in the context of the Signal protocol and the Age encryption tool.

From what I understand, there is no security problem with using the same scalars, `d`, both for ECDH input `[d]G` and for signature. The problem is more about key lifecycle management. See 

* https://crypto.stackexchange.com/questions/3260/using-same-keypair-for-diffie-hellman-and-signing 
* https://crypto.stackexchange.com/questions/14662/using-ecdsa-keys-for-encryption

And the way we use `d` is not entirely the same as the examples in those links. In those links they discuss using the exact same key. We use different keys. Specifically, assuming random oracle output `random` with input `d`, we have for derived keys `f(d,random)` in a mod N world, which is indistinguishable from a random key, no?

**Comment by sander-cb** [comment]
In the StackOverflow answers I do see some more concerns regarding security of reuse of the same key pair for signing and key agreement. Indeed these concerns should not apply to the derived signing key, but note that the original signing key is also applied for PoP before applying it in ECDH. A key compromise could enable the Verifier to reuse the same PID to response another Verifier’s challenge.

I see three options:

- find a security proof for cross-protocol attack resistance: prove the claim that reusing `d` for ECDH input `[d]G` does not compromise `d` for use in the selected PoP algorithms
- let the user generate an ephemeral ECDH key pair, if we don’t need special properties anyway, and store sufficient key derivation material in/along with the attestation
- haven’t thought this one through, but: perform some form of deterministic key blinding over `d` and `[d]G` before inputting it into ECDH, e.g. with a blinding factor derived from a hash of the protocol transcript so far

Found the related Age post by the way: [Using Ed25519 signing keys for encryption](https://words.filippo.io/using-ed25519-keys-for-encryption/):

> What remains open for future work is checking for cross-protocol attacks. The only one that really concerns me is if a partial decryption oracle (where you can submit files to an endpoint and it will tell you if they decrypt successfully) allows generating an Ed25519 signature that can be used to log in to an SSH server. I can't see such an attack, but if you can, let me know on Twitter.

Edit: I now realise that another concern may be technical feasability on Android/iOS. Possibly a root key generated for one protocol cannot technically be reused for the other.

**Comment by emlun** [comment]
> I now realise that another concern may be technical feasability on Android/iOS. Possibly a root key generated for one protocol cannot technically be reused for the other.

This could also be an issue with some key representations. For example, the [COSE elliptic curve identifiers](https://www.iana.org/assignments/cose/cose.xhtml#elliptic-curves) `4 (X25519)` and `6 (Ed25519)` are restricted for use only with ECDH and EdDSA, respectively, and there are currently no registrations of identifiers for both uses of the Edwards curves.

**Comment by sander** [comment]
In the current draft at https://github.com/sander/hierarchical-deterministic-keys we apply ARKG. In this process I’ve found several new issues which I will file in that repository. At the same time, several relevant improvements have been made to ARKG.
